services:
  db:
    image: mariadb
    restart: always
    user: root
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_DATABASE=example
    expose:
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  frontend:
    build:
      context: frontend
    volumes:
      - frontend_dist:${FRONTEND_BUILD_DIR}

  service_1:
    container_name: service_1
    build:
      context: .
      args:
        - BACKEND_DIR=${BACKEND_DIR}
    ports:
      - '[::1]:9000:9000'

    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_password

    environment:
      - PASSWORD_FILE_PATH=/run/secrets/db_password
      - DB_HOST=db
      - DB_NAME=example
      - DB_USER=root
    networks:
      - fpm_net
  proxy:
    image: nginx:1.29-alpine-slim
    volumes:
      - frontend_dist:${FRONTEND_BUILD_DIR}
      - ./nginx:/etc/nginx/templates
    ports:
      - 80:80
    networks:
      - fpm_net
    environment:
      - FRONTEND_BUILD_DIR
      - BACKEND_DIR

    depends_on:
      service_1:
        condition: service_started
      frontend:
        condition: service_completed_successfully

volumes:
  db_data:
  frontend_dist:

secrets:
  db_password:
    file: db/password.txt
networks:
  fpm_net: